### ISSUE TITLE
Missing attribution to MinecraftStats

### ISSUE THREAD

**Issue by pdinklag** [smashedbotatos/iCarey_Whitelist_System#1]
You use [MinecraftStats](https://github.com/pdinklag/MinecraftStats) in your project. Awesome, I'm stoked about that!

I released it under the [Creative Commons BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) license so everyone can use it. However, it does state an _Attribution_ part that requires you to at least provide a link to the original - which I also just clarified in the original repository. In your project, you removed any and all references to MinecraftStats.

There's a lot of work in the project and I'd like people to at least recognize that. A simple link in the footer (e.g., next to your copyright) will be fine and won't hurt you. Thanks! :smile: 

PS: I also suggest to update it, because it can handle much larger player numbers now after some core improvements.

**Comment by smashedbotatos** [comment]
Yes! I love your work on it. I will absolutely give credit where credit is due. I heavily modified your html code and imported it in to my project. I am sorry I have not added back the attributions as of yet. I will make sure they are back in the next update I do. Also I will try and use the updated version. :)

If you would like to clone the repo and add the attribution to the stats.php page then make a pull request. I would be grateful for that! It will save me some time as I try to write the WIKI. Installation for my project seems to be a bit more complicated than people realize. 

Thank you for bringing this to my attention!!

**Comment by smashedbotatos** [comment]
I have fixed it! Updated the program, and kept the attribution. Have a look here at the test site. 
https://mc.icarey.net/testing/stats.php

Reference the following commit for changes https://github.com/smashedbotatos/iCarey_Whitelist_System/commit/cf93d3983f15838a22859781d6a36e8f44cb458f

Let me know if that is acceptable.

**Comment by smashedbotatos** [comment]
#cf93d3983f15838a22859781d6a36e8f44cb458f

**Comment by pdinklag** [comment]
All good!
As said, I'm already content with a link, the copyright isn't even needed if you don't want that. Thanks! 👍 And thanks for the interest in the project!
